import os
from dotenv import load_dotenv

load_dotenv()

CAPITAL = 100000
MAX_PARTS = 5
NORMAL_TRADE = 10000
LARGE_TRADE_MIN = 20000
LARGE_TRADE_MAX = 30000
NIKKEI_LARGE_MOVE_THRESHOLD = 1000

AI_PROVIDER = "openai"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
EMAIL_FROM = os.getenv("EMAIL_FROM")
EMAIL_TO = os.getenv("EMAIL_TO")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "465"))

LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN")
LINE_USER_ID = os.getenv("LINE_USER_ID")
ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")

